# Generated by Django 5.2.7 on 2025-10-15 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ean', models.CharField(max_length=13, unique=True)),
                ('type', models.CharField(choices=[('wine', 'Vino'), ('beer', 'Birra'), ('liquor', 'Liquore')], max_length=10)),
                ('description', models.TextField(blank=True)),
                ('origin', models.CharField(blank=True, max_length=50)),
                ('abv', models.CharField(blank=True, max_length=10)),
                ('image', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='FoodPairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_pairings', to='api.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cocktail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('liquors', models.ManyToManyField(related_name='cocktails', to='api.product')),
            ],
        ),
    ]
