# Generated by Django 5.2.7 on 2025-10-15 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='ean',
            new_name='barcode',
        ),
    ]
