# Generated by Django 5.2.7 on 2025-10-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_ean_product_barcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('vino', 'Vino'), ('birra', 'Birra'), ('liquore', 'Liquore')], max_length=10),
        ),
    ]
