# Generated by Django 5.2.7 on 2025-10-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cocktail',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='foodpairing',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
